# yaml-language-server: $schema=config.schema.json
mqtt:
  host: ""
  port: 1883
  authentication: true
  password: "234"
  user: "mqtt"

# TODO: Consider adding an auto-off setting for out mode
# Add default setting (also only for out)
topics:
  - topic: "" # The pin id is appended as /<id> to the topic.
    pin: 0
    mode: "in"
    offTimeout: -1 # -1 disables automatic switch off of the pin

pollInterval: 100
