# yaml-language-server: $schema=config.schema.json
mqtt:
  host: ""
  port: 1883
  authentication: true
  password: "234"
  user: "mqtt"

# TODO: Consider adding an auto-off setting for out mode
# Add default setting (also only for out)
topics:
  - topic: ""
    pin: 0
    mode: "in"

pollInterval: 100
